version: '3'
services:
  videos:
    build: '.'
    ports:
      - "3000:3000"
    depends_on: 
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb/videos
  
  mongodb:
    image: mongo
    ports:
      - "27000:27017"

  mongodb_seed:
    build: './mongo-seed'
    links:
      - mongodb
